# 網站基本資訊
title: 我的網站
description: 這是一個使用 Jekyll 建立的網站
author: 你的名字

# 網站 URL
url: "https://yourusername.github.io" # 你的 GitHub Pages 網址
baseurl: ""  # 若你的網站不是放在子資料夾就留空

# 主題設定
theme: minima  # 預設主題，可換成其他 Jekyll 主題名稱

# 外掛（GitHub Pages 預設支援以下兩個）
plugins:
  - jekyll-feed      # 自動產生 RSS Feed
  - jekyll-seo-tag   # SEO 基本標籤

# 預設文章設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "你的名字"

# 導覽列選單（可選）
nav_links:
  - title: "首頁"
    url: "/"
  - title: "文章"
    url: "/blog"
  - title: "關於我"
    url: "/about"
